# Generated by Django 5.2.7 on 2025-10-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('experience_level', models.CharField(max_length=100)),
                ('contract_type', models.CharField(max_length=100)),
                ('salary', models.CharField(blank=True, max_length=10, null=True)),
                ('location', models.CharField(max_length=255)),
                ('published_date', models.DateField()),
                ('city', models.CharField(max_length=100)),
                ('enterprise', models.CharField(max_length=255)),
                ('other_details', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
    ]
