export const jobsMock = [
    {
      id: 1,
      title: 'Senior Frontend Developer',
      company: 'TechCorp Inc.',
      skills: ['React', 'TypeScript', 'Tailwind'],
      city: 'Paris',
      platform: 'LinkedIn',
      link: 'https://linkedin.com/jobs/1',
      postedDays: 2,
      description: 'We are looking for an experienced Frontend Developer to join our dynamic team. You will work on cutting-edge web applications using modern technologies.',
      requirements: '5+ years experience, Strong React skills, Team player',
      salary: '€60,000 - €80,000'
    },
    {
      id: 2,
      title: 'Full Stack Engineer',
      company: 'StartupXYZ',
      skills: ['Node.js', 'React', 'MongoDB'],
      city: 'Lyon',
      platform: 'Indeed',
      link: 'https://indeed.com/jobs/2',
      postedDays: 5,
      description: 'Join our innovative startup as a Full Stack Engineer. Work on exciting projects with modern tech stack.',
      requirements: '3+ years experience, Full stack knowledge, Agile methodology',
      salary: '€50,000 - €70,000'
    },
    {
      id: 3,
      title: 'Backend Developer',
      company: 'DataFlow Solutions',
      skills: ['Python', 'Django', 'PostgreSQL'],
      city: 'Marseille',
      platform: 'Glassdoor',
      link: 'https://glassdoor.com/jobs/3',
      postedDays: 1,
      description: 'Looking for a Backend Developer to build scalable APIs and microservices.',
      requirements: '4+ years Python, Database expertise, API design',
      salary: '€55,000 - €75,000'
    },
    {
      id: 4,
      title: 'DevOps Engineer',
      company: 'CloudMasters',
      skills: ['AWS', 'Docker', 'Kubernetes'],
      city: 'Toulouse',
      platform: 'LinkedIn',
      link: 'https://linkedin.com/jobs/4',
      postedDays: 3,
      description: 'Seeking DevOps Engineer to manage our cloud infrastructure and CI/CD pipelines.',
      requirements: 'AWS certified, Container orchestration, Automation skills',
      salary: '€65,000 - €85,000'
    },
    {
      id: 5,
      title: 'UI/UX Designer',
      company: 'DesignHub',
      skills: ['Figma', 'Adobe XD', 'Prototyping'],
      city: 'Paris',
      platform: 'Indeed',
      link: 'https://indeed.com/jobs/5',
      postedDays: 7,
      description: 'Creative UI/UX Designer needed to craft beautiful user experiences.',
      requirements: 'Strong portfolio, User research, Design systems',
      salary: '€45,000 - €60,000'
    },
    {
      id: 6,
      title: 'Mobile Developer',
      company: 'AppFactory',
      skills: ['React Native', 'iOS', 'Android'],
      city: 'Nice',
      platform: 'Glassdoor',
      link: 'https://glassdoor.com/jobs/6',
      postedDays: 10,
      description: 'Mobile Developer to create cross-platform applications for millions of users.',
      requirements: 'Mobile development experience, App store deployment, Performance optimization',
      salary: '€50,000 - €70,000'
    },
    {
      id: 7,
      title: 'Data Scientist',
      company: 'AI Innovations',
      skills: ['Python', 'Machine Learning', 'TensorFlow'],
      city: 'Paris',
      platform: 'LinkedIn',
      link: 'https://linkedin.com/jobs/7',
      postedDays: 4,
      description: 'Data Scientist to develop ML models and drive data-driven decision making.',
      requirements: 'PhD or Masters, ML expertise, Statistical analysis',
      salary: '€70,000 - €90,000'
    },
    {
      id: 8,
      title: 'Product Manager',
      company: 'ProductPro',
      skills: ['Agile', 'Roadmapping', 'Analytics'],
      city: 'Lyon',
      platform: 'Indeed',
      link: 'https://indeed.com/jobs/8',
      postedDays: 15,
      description: 'Product Manager to lead product strategy and collaborate with engineering teams.',
      requirements: '5+ years PM experience, Technical background, Stakeholder management',
      salary: '€60,000 - €80,000'
    },
    {
      id: 9,
      title: 'Security Engineer',
      company: 'SecureNet',
      skills: ['Cybersecurity', 'Penetration Testing', 'Network Security'],
      city: 'Bordeaux',
      platform: 'Glassdoor',
      link: 'https://glassdoor.com/jobs/9',
      postedDays: 6,
      description: 'Security Engineer to protect our infrastructure and conduct security audits.',
      requirements: 'Security certifications, Vulnerability assessment, Incident response',
      salary: '€65,000 - €85,000'
    },
    {
      id: 10,
      title: 'QA Engineer',
      company: 'QualityFirst',
      skills: ['Selenium', 'Jest', 'Test Automation'],
      city: 'Nantes',
      platform: 'LinkedIn',
      link: 'https://linkedin.com/jobs/10',
      postedDays: 8,
      description: 'QA Engineer to ensure quality through automated testing and manual QA.',
      requirements: 'Test automation, CI/CD integration, Bug tracking',
      salary: '€45,000 - €60,000'
    },
    {
      id: 11,
      title: 'Tech Lead',
      company: 'InnovateTech',
      skills: ['Leadership', 'Architecture', 'Java'],
      city: 'Paris',
      platform: 'Indeed',
      link: 'https://indeed.com/jobs/11',
      postedDays: 12,
      description: 'Tech Lead to guide development team and make architectural decisions.',
      requirements: '8+ years experience, Team leadership, System design',
      salary: '€75,000 - €95,000'
    },
    {
      id: 12,
      title: 'Frontend Developer',
      company: 'WebSolutions',
      skills: ['Vue.js', 'CSS', 'JavaScript'],
      city: 'Lille',
      platform: 'Glassdoor',
      link: 'https://glassdoor.com/jobs/12',
      postedDays: 20,
      description: 'Frontend Developer to build responsive and accessible web applications.',
      requirements: '3+ years, Modern JavaScript, Responsive design',
      salary: '€45,000 - €60,000'
    }
  ];
