# Generated by Django 5.2.7 on 2025-11-23 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('sector', models.CharField(blank=True, max_length=255)),
                ('other_details', models.TextField()),
            ],
            options={
                'db_table': 'entreprises',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('experience_level', models.CharField(max_length=255)),
                ('contract_type', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('published_date', models.DateField()),
                ('platform', models.CharField(max_length=255)),
                ('skills', models.JSONField(blank=True)),
                ('link', models.TextField(blank=True)),
                ('other_details', models.TextField()),
                ('enterprise', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='job.entreprise')),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
    ]
