# Generated by Django 5.2.7 on 2025-11-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='published_date',
            field=models.CharField(max_length=255),
        ),
    ]
