# Generated by Django 5.2.7 on 2026-02-05 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_job_published_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entreprise',
            old_name='other_details',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='other_details',
            new_name='description',
        ),
    ]
