# Generated by Django 5.2.7 on 2026-02-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_rename_other_details_entreprise_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='enterprise',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Entreprise',
        ),
    ]
