# Generated by Django 5.2.7 on 2026-02-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_job_enterprise_delete_entreprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='link',
            field=models.TextField(blank=True, unique=True),
        ),
    ]
