# Generated by Django 5.2.7 on 2026-02-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_job_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='condidate',
            field=models.BooleanField(default=False),
        ),
    ]
